/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Cadastrar;

import DAO.Conexao;
import DAO.PacienteDAO;
import DAO.ConsultaDAO;
import Modelo.Consulta;
import Modelo.Paciente;
import Principal.home;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Alcantara
 */
public class CadastrarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarConsulta
     */
    public CadastrarConsulta() {
        initComponents();
        setSize(600, 440);
        setLocationRelativeTo(this);
        AtualizaCombo();
    }
        private void AtualizaCombo() {
        Connection con = Conexao.AbrirConexao();
        PacienteDAO sql = new PacienteDAO(con);
        List<Paciente> lista = new ArrayList<>();
        lista = sql.ListarComboPaciente();
        Combopa.addItem("");
        
        for (Paciente b : lista) {
            Combopa.addItem(b.getNome());
        }
        
        Conexao.FecharConexao(con);
    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Combopa = new javax.swing.JComboBox<>();
        jTF_IdP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_DataCad = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_DataCons = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboMed = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Consulta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 100);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 300, 0, 0);

        jLabel2.setText("PACIENTE:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 80, 30);

        Combopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombopaActionPerformed(evt);
            }
        });
        jPanel2.add(Combopa);
        Combopa.setBounds(240, 20, 180, 30);
        jPanel2.add(jTF_IdP);
        jTF_IdP.setBounds(90, 20, 130, 30);

        jLabel4.setText("DATA DE HOJE:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60, 70, 90, 30);

        try {
            jTF_DataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTF_DataCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_DataCadActionPerformed(evt);
            }
        });
        jPanel2.add(jTF_DataCad);
        jTF_DataCad.setBounds(160, 70, 180, 30);

        jLabel5.setText("DATA DA CONSULTA:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 120, 130, 30);

        try {
            jTF_DataCons.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jTF_DataCons);
        jTF_DataCons.setBounds(160, 120, 180, 30);

        jLabel6.setText("CONSULTA:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 170, 70, 30);

        ComboMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DENTISTA", "CARDIOLOGISTA", "OFTAMOLOGISTA", "OTORRINNOLARIGOLOGISTA", "GINECOLOGISTA", "DERMATOLOGISTA", "GERIÁTRA", "PEDIATRA", "PROCTOLOGISTA", "EXAME DE SANGUE", "FISIOTERAPEUTA", "NUTRICIONISTA", "NEONATOLOGISTA", "PATOLOGISTA", "OBSTETRA", "NEOROLOGISTA", "PSIQUIÁTRA", "NEOFROLOGISTA", "UROLOGISTA", "GASTROENTEROLOGISTA", "COLOPROCTOLOGISTA", "ORTOPEDISTA", "IMUNOLOGISTA", "ANGIOLOGISTA", "CANCERLOROGISTA", "INODOCRINOLOGISTA" }));
        jPanel2.add(ComboMed);
        ComboMed.setBounds(160, 170, 180, 30);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(60, 250, 120, 40);

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(430, 250, 110, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro Alcantara\\Pictures\\Nova pasta\\LOGO.png")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 10, 200, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro Alcantara\\Pictures\\Nova pasta\\TELEMEDICINA-MORSCH_header_19_8_2016.png")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(-70, -10, 780, 250);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 620, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Principal.home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = (String) Combopa.getSelectedItem();
        String idpaciente = jTF_IdP.getText();
        String datacad = jTF_DataCad.getText();
        String datacons = jTF_DataCons.getText();
        String medico = (String) ComboMed.getSelectedItem();
       
        
        if (nome.equals("") || datacad.equals("") || datacons.equals("") || medico.equals("")) {
            
            JOptionPane.showMessageDialog(null, "Nenhum campo está vazio", 
                    "Centro Medico", JOptionPane.WARNING_MESSAGE);
        } else {
            Connection con = Conexao.AbrirConexao();
            ConsultaDAO sql = new ConsultaDAO(con);
            int n = Integer.parseInt(idpaciente);
            Consulta a = new Consulta();
            
            a.setNome(nome);
            a.setIdp(n);
            a.setDatacad(datacad);
            a.setDatacons(datacons);
            a.setMedico(medico);

            
            
            sql.Inserir_Consulta(a);
            Conexao.FecharConexao(con);
            
           
            jTF_DataCad.setText("");
            jTF_DataCons.setText("");
            jTF_IdP.setText("");
            
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso",
                    "Centro Medico", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new home().setVisible(true);
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CombopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombopaActionPerformed
       Connection con = Conexao.AbrirConexao();
        PacienteDAO sql = new PacienteDAO(con);
        List<Paciente> lista = new ArrayList<>();
        String nome = Combopa.getSelectedItem().toString();
        
        lista = sql.ConsultarCodigoPaciente(nome);
        
        for (Paciente b : lista) {
            int a = b.getId();
            jTF_IdP.setText("" + a);
        }
        
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_CombopaActionPerformed

    private void jTF_DataCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_DataCadActionPerformed
       

    }//GEN-LAST:event_jTF_DataCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMed;
    private javax.swing.JComboBox<String> Combopa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField jTF_DataCad;
    private javax.swing.JFormattedTextField jTF_DataCons;
    private javax.swing.JTextField jTF_IdP;
    // End of variables declaration//GEN-END:variables
}
