/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Excluir;

import DAO.Conexao;
import DAO.PacienteDAO;
import Modelo.Paciente;
import Principal.home;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Alcantara
 */
public class CancelarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form CancelarConsulta
     */
    public CancelarConsulta() {
        initComponents();
        setSize(710,390);
        setLocationRelativeTo(this);
        AtualizaCombo();
    }
    private void AtualizaCombo() {
        Connection con = Conexao.AbrirConexao();
        PacienteDAO sql = new PacienteDAO(con);
        List<Paciente> lista = new ArrayList<>();
        lista = sql.ListarComboPaciente();
        Combopa.addItem("");
        
        for (Paciente b : lista) {
            Combopa.addItem(b.getNome());
        }
        
        Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Combopa = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        idCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("CANCELAMENTO DE CONSULTA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 670, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NOME DO PACIENTE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 170, 30);

        Combopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombopaActionPerformed(evt);
            }
        });
        getContentPane().add(Combopa);
        Combopa.setBounds(240, 110, 320, 30);

        jSeparator1.setToolTipText("");
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 700, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 210, 120, 70);

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setText("APAGAR CONSULTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 210, 160, 70);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setText("CANCELAR");
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 210, 110, 70);
        getContentPane().add(idCli);
        idCli.setBounds(180, 110, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro Alcantara\\Pictures\\Nova pasta\\coisa biruleta para bicho do negocio.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-220, -110, 920, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CombopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombopaActionPerformed
        Connection con = Conexao.AbrirConexao();
        PacienteDAO sql = new PacienteDAO(con);
        List<Paciente> lista = new ArrayList<>();
        String nome = Combopa.getSelectedItem().toString();
        
        lista = sql.ConsultarCodigoPaciente(nome);
        
        for (Paciente b : lista) {
            int a = b.getId();
            idCli.setText("" + a);
        }
        
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_CombopaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigo = idCli.getText();
        String nome = Combopa.getSelectedItem().toString();
        
        Connection con = Conexao.AbrirConexao();
        PacienteDAO sql = new PacienteDAO(con);
        Paciente a = new Paciente();
        
        if (nome.equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum nome selecionado",
                    "Vídeo Locadora", JOptionPane.WARNING_MESSAGE);
        } else {
            int b = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir"
                    + "\n ( " + codigo + " ) ( " + nome + " ) ", "Vídeo Locadora",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (b == 0) {
                int cod = Integer.parseInt(codigo);
                a.setNome(nome);
                a.setId(cod);
                sql.Excluir_Paciente(a);
                Conexao.FecharConexao(con);
                dispose();
                new home().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combopa;
    private javax.swing.JTextField idCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
